'use strict';
window.createGlaciaClose=({root,api,icons})=>{
 const shade=document.createElement('div');shade.className='wb-modal-shade wb-close-shade';shade.hidden=true;
 shade.innerHTML=`<section class="wb-modal wb-close-dialog" role="dialog" aria-modal="true" aria-labelledby="wb-close-title" aria-describedby="wb-close-message"><div class="wb-close-mark" aria-hidden="true"><span class="wb-brand-mark"></span></div><div class="wb-modal-head"><h2 id="wb-close-title">Close Glacia?</h2><button class="wb-icon-button cursor-interaction" data-close-choice="cancel" aria-label="Close dialog"><i data-lucide="x" aria-hidden="true"></i></button></div><p id="wb-close-message">Keep Glacia in the system tray or exit the app?</p><label class="wb-close-remember"><input id="wb-close-remember" type="checkbox"><span>Don't ask me again</span></label><div class="wb-close-actions"><button class="wb-primary cursor-interaction" data-close-choice="tray"><i data-lucide="panel-bottom" aria-hidden="true"></i>Minimize to tray</button><button class="wb-secondary cursor-interaction" data-close-choice="exit"><i data-lucide="log-out" aria-hidden="true"></i>Exit app</button><button class="wb-secondary cursor-interaction" data-close-choice="cancel">Cancel</button></div><p class="wb-form-error" role="alert" hidden></p></section>`;
 root.append(shade);let active=false,pending=false,previousFocus;const underlying=()=>[root.querySelector('.wb-shell'),root.querySelector('#wb-modal-shade'),root.querySelector('.wb-update-shade')].filter(Boolean);const savedInert=new Map();
 function show(){if(active)return;active=true;previousFocus=document.activeElement;shade.hidden=false;shade.querySelector('input').checked=false;shade.querySelector('[role=alert]').hidden=true;for(const element of underlying()){savedInert.set(element,element.inert);element.inert=true;}icons();shade.querySelector('[data-close-choice=tray]').focus();}
 function hide(){shade.hidden=true;active=false;for(const element of underlying())element.inert=savedInert.get(element)||false;savedInert.clear();root.querySelector('.wb-shell').inert=!root.querySelector('#wb-modal-shade').hidden||!!root.querySelector('.wb-update-shade:not([hidden])');if(previousFocus?.isConnected&&!previousFocus.closest('[inert]'))previousFocus.focus();}
 async function choose(action){if(pending)return;pending=true;const buttons=[...shade.querySelectorAll('button')];buttons.forEach(button=>button.disabled=true);try{await api.closeDecision({action,remember:shade.querySelector('input').checked});hide();}catch(error){const notice=shade.querySelector('[role=alert]');notice.textContent=error.message;notice.hidden=false;}finally{pending=false;buttons.forEach(button=>button.disabled=false);}}
 root.addEventListener('click',event=>{const button=event.target.closest('[data-close-choice]');if(!button)return;event.stopImmediatePropagation();event.preventDefault();if(active&&!button.disabled)choose(button.dataset.closeChoice);},true);
 root.addEventListener('keydown',event=>{if(!active)return;event.stopImmediatePropagation();if(event.key==='Escape'){event.preventDefault();choose('cancel');}if(event.key==='Tab'){const controls=[...shade.querySelectorAll('button:not(:disabled),input:not(:disabled)')],first=controls[0],last=controls.at(-1);if(!first){event.preventDefault();return;}if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}},true);
 const observer=new MutationObserver(()=>{if(active)for(const element of underlying())if(!element.inert)element.inert=true;});observer.observe(root,{subtree:true,attributes:true,attributeFilter:['inert','hidden']});
 api.onCloseRequested(show);api.onLocked(()=>{if(active)root.querySelector('.wb-shell').inert=true;});return {get active(){return active;}};
};
