'use strict';
(()=>{const api=window.winterbell,q=s=>document.querySelector(s);let selectedId='',current=null,menuSignature='',polling=false,feedbackTimer;
const languageView=window.createGlaciaLanguageView(q('#mini-root'));api.onLanguageChanged?.(value=>languageView.setLanguage(value));
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons=()=>window.lucide?.createIcons();
async function closePicker(){q('#mini-menu').hidden=true;q('#mini-picker').setAttribute('aria-expanded','false');await api.trayMenuOpen({open:false});}
function render(data){current=data;languageView.setLanguage(data.preferences.language);q('#mini-root').dataset.theme=data.preferences.dark?'dark':'light';const available=!data.locked&&data.accounts.length>0;q('#mini-root').dataset.ready=String(available);q('#mini-key').hidden=!available;q('#mini-message').hidden=available;q('#mini-picker').disabled=!available;
 if(!available){q('#mini-code').textContent='';q('#mini-name').textContent='Glacia';q('#mini-email').textContent='';q('#mini-menu').innerHTML='';menuSignature='';q('#mini-message').textContent=data.locked?'Open Glacia to unlock your vault.':'Add an authenticator in Glacia to see it here.';if(!q('#mini-menu').hidden)closePicker().catch(()=>{});return;}
 const chosen=data.accounts.find(a=>a.id===(selectedId||data.preferences.trayAccountId))||data.accounts[0];selectedId=chosen.id;q('#mini-name').textContent=chosen.name;q('#mini-email').textContent=chosen.email;const point=chosen.code.length/2;q('#mini-code').textContent=chosen.code.slice(0,point)+' '+chosen.code.slice(point);q('#mini-code').classList.toggle('is-expiring',chosen.remaining<=5);q('#mini-progress').value=chosen.remaining/chosen.period*100;q('#mini-time').textContent=chosen.remaining+'s remaining';
 const signature=JSON.stringify(data.accounts.map(a=>[a.id,a.name,a.email,chosen.id]));if(signature!==menuSignature){menuSignature=signature;q('#mini-menu').innerHTML=data.accounts.map(a=>`<button class="mini-account" data-account="${a.id}" aria-pressed="${a.id===chosen.id}"><strong>${safe(a.name)}</strong><small>${safe(a.email)}</small></button>`).join('');}
 q('#mini-picker').disabled=data.accounts.length<2;
}
async function refresh(){if(polling)return;polling=true;try{render(await api.status());}catch{q('#mini-code').textContent='';q('#mini-message').hidden=false;q('#mini-message').textContent='Open Glacia to reconnect.';}finally{polling=false;}}
q('#mini-picker').addEventListener('click',async()=>{const open=q('#mini-menu').hidden;await api.trayMenuOpen({open});q('#mini-menu').hidden=!open;q('#mini-picker').setAttribute('aria-expanded',String(open));if(open)q('.mini-account[aria-pressed=true]')?.focus();});
q('#mini-menu').addEventListener('click',async event=>{const button=event.target.closest('[data-account]');if(!button)return;try{selectedId=button.dataset.account;render(await api.traySelect({id:selectedId}));await closePicker();q('#mini-picker').focus();}catch{await refresh();}});
q('#mini-copy').addEventListener('click',async()=>{if(!selectedId||current?.locked)return;try{await api.copy({id:selectedId});q('#mini-feedback').textContent='Copied';clearTimeout(feedbackTimer);feedbackTimer=setTimeout(()=>q('#mini-feedback').textContent='',1500);}catch{await refresh();}});
q('#mini-open').addEventListener('click',()=>api.openMainWindow());q('#mini-hide').addEventListener('click',()=>api.closeMiniWindow());document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(!q('#mini-menu').hidden)closePicker();else api.closeMiniWindow();}});document.addEventListener('pointerdown',()=>api.touch().catch(()=>{}));api.onLocked(()=>{if(current)render({...current,locked:true,accounts:[]});});api.onMiniReset(()=>{q('#mini-menu').hidden=true;q('#mini-picker').setAttribute('aria-expanded','false');refresh();});icons();refresh();setInterval(()=>{if(!document.hidden)refresh();},1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});})();
