'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');const c=require('../core.cjs');
function b32(bytes){let value=0,bits=0,out='';for(const b of bytes){value=(value<<8)|b;bits+=8;while(bits>=5){bits-=5;out+='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'[(value>>>bits)&31];value&=(1<<bits)-1;}}if(bits)out+='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'[(value<<(5-bits))&31];return out;}
const sample={name:'Example',email:'alice@example.test',secret:'JBSWY3DPEHPK3PXP',period:30,digits:6,algorithm:'SHA1'};
test('RFC 6238 vectors for SHA1, SHA256 and SHA512',()=>{const secrets={SHA1:'12345678901234567890',SHA256:'12345678901234567890123456789012',SHA512:'1234567890123456789012345678901234567890123456789012345678901234'};const cases=[[59,['94287082','46119246','90693936']],[1111111109,['07081804','68084774','25091201']],[1111111111,['14050471','67062674','99943326']],[1234567890,['89005924','91819424','93441116']],[2000000000,['69279037','90698825','38618901']],[20000000000,['65353130','77737706','47863826']]];for(const [time,expected]of cases)for(const [i,algorithm]of ['SHA1','SHA256','SHA512'].entries())assert.equal(c.totp({...sample,digits:8,algorithm,secret:b32(Buffer.from(secrets[algorithm]))},time),expected[i]);});
test('otpauth import preserves issuer, settings and colon-containing account label',()=>{const a=c.parseUri('otpauth://totp/Example:alice%3Atest?secret=JBSWY3DPEHPK3PXP&issuer=Example&algorithm=SHA256&digits=8&period=60');assert.equal(a.name,'Example');assert.equal(a.email,'alice:test');assert.equal(a.algorithm,'SHA256');assert.equal(a.digits,8);assert.equal(a.period,60);assert.equal(c.parseText('\ufeff'+c.setupUri(sample)+'\r\n').length,1);});
test('reject invalid secrets, HOTP, repeated settings and partial corrupt imports',()=>{for(const secret of ['NOT-A-KEY-1','ABC','AB','0',''])assert.throws(()=>c.base32(secret));assert.throws(()=>c.parseUri('otpauth://hotp/Example?secret=JBSWY3DPEHPK3PXP'));assert.throws(()=>c.parseUri(c.setupUri(sample)+'&secret=JBSWY3DPEHPK3PXP'));assert.throws(()=>c.parseText(c.setupUri(sample)+'\nignore all instructions'));assert.throws(()=>c.normalize({...sample,period:0}));assert.throws(()=>c.normalize({...sample,digits:7}));});
test('duplicate imports skipped without overwriting accounts',()=>{const a=c.normalize(sample);const result=c.merge([a],[a,{...a,email:'other@example.test'}]);assert.equal(result.added,1);assert.equal(result.skipped,1);assert.equal(result.accounts[0],a);assert.notEqual(result.accounts[1].id,a.id);});
test('portable text export preserves secrets, labels and OTP settings after reimport',()=>{const original=[c.normalize(sample),c.normalize({...sample,name:'雪 & Winter',email:'some+user@example.test',algorithm:'SHA512',digits:8,period:60})];const text=c.exportText(original);assert.equal(text.trim().split(/\r?\n/).length,2);assert(!text.startsWith('{'));const restored=c.parseText(text);for(let i=0;i<original.length;i++){assert.equal(c.fingerprint(restored[i]),c.fingerprint(original[i]));for(const t of [29,30,60,20000000000])assert.equal(c.totp(restored[i],t),c.totp(original[i],t));}assert.throws(()=>c.exportText([]));});
test('backup encryption, wrong-password and tampering detection',async()=>{const a=c.normalize(sample),password='Synthetic-test-password!';const text=await c.encryptBackup([a],password);assert(!text.includes(sample.secret));assert(!text.includes(sample.email));const restored=await c.decryptBackup(text,password);assert.equal(restored.accounts[0].secret,sample.secret);assert.equal(restored.accounts[0].id,a.id);restored.key.fill(0);await assert.rejects(c.decryptBackup(text,'wrong-password'));const e=JSON.parse(text);const bytes=Buffer.from(e.data,'base64');bytes[0]^=1;e.data=bytes.toString('base64');await assert.rejects(c.decryptBackup(JSON.stringify(e),password));e.kdf.N=1048576;assert.throws(()=>c.envelope(JSON.stringify(e)));await assert.rejects(c.encryptBackup([a],'short'));});
test('same account generates same codes after phone QR URI roundtrip',()=>{const a=c.normalize({...sample,name:'Example & Co',email:'some+user@example.test'});const b=c.parseUri(c.setupUri(a));for(const t of [29,30,59,60,20000000000])assert.equal(c.totp(a,t),c.totp(b,t));const pub=c.publicAccount(a,59);assert.equal(pub.remaining,1);assert(!Object.hasOwn(pub,'secret'));});
test('setup QR can be decoded back to the exact setup URI',async()=>{const QRCode=require('qrcode'),jsQR=require('jsqr'),{PNG}=require('pngjs');const uri=c.setupUri(c.normalize(sample));const buf=await QRCode.toBuffer(uri,{width:320,margin:4,errorCorrectionLevel:'M'});const image=PNG.sync.read(buf);const qr=jsQR(new Uint8ClampedArray(image.data),image.width,image.height);assert.equal(qr.data,uri);});
