'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),core=require('../core.cjs'),{parseMigration,collectMigration}=require('../migration.cjs'),{migrationUri,field}=require('./migration-fixture.cjs');
const record=(name='Demo')=>({name,email:'demo@example.invalid',secret:'GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ',algorithm:'SHA1',digits:6});
test('Google transfer preserves byte secrets, issuer, labels and SHA settings',()=>{const input=[record(),{...record('SHA256'),algorithm:'SHA256',digits:8,email:'SHA256:user:account'}],parsed=parseMigration(migrationUri(input));assert.equal(parsed.records.length,2);assert.equal(parsed.records[1].email,'user:account');for(let i=0;i<input.length;i++){assert.equal(parsed.records[i].secret,input[i].secret);assert.equal(parsed.records[i].algorithm,input[i].algorithm);assert.equal(parsed.records[i].digits,input[i].digits);for(const t of [59,60,1234567890])assert.equal(core.totp(parsed.records[i],t),core.totp({...input[i],period:30},t));}});
test('Google transfer QR image round trip decodes the complete multi-account payload',async()=>{const QRCode=require('qrcode'),jsQR=require('jsqr'),{PNG}=require('pngjs'),uri=migrationUri([record('First'),record('Second')],{version:2}),image=PNG.sync.read(await QRCode.toBuffer(uri,{width:650,margin:4})),found=jsQR(new Uint8ClampedArray(image.data),image.width,image.height);assert.equal(parseMigration(found.data).records.length,2);});
test('all pages are collected out of order, repeated pages do not duplicate keys, mixed transfers fail',()=>{const first=parseMigration(migrationUri([record('First')],{size:2,index:0})),last=parseMigration(migrationUri([record('Last')],{size:2,index:1}));let batch=collectMigration(null,last);assert.deepEqual(batch.missing,[0]);batch=collectMigration(batch,last);assert.equal(batch.records.length,1);batch=collectMigration(batch,first);assert.deepEqual(batch.missing,[]);assert.deepEqual(batch.records.map(r=>r.name),['First','Last']);assert.throws(()=>collectMigration(batch,parseMigration(migrationUri([record()],{size:2,id:99}))),/another transfer/);assert.throws(()=>collectMigration(batch,parseMigration(migrationUri([record('Conflicting')],{size:2}))),/conflicts/);});
test('malformed and unsupported transfer data is rejected instead of partially imported',()=>{for(const options of [{size:0},{size:2,index:2},{version:2147483648}])assert.throws(()=>parseMigration(migrationUri([record()],options)));assert.throws(()=>parseMigration(migrationUri([record(),{...record(),type:1}])),/HOTP/);assert.throws(()=>parseMigration(migrationUri([{...record(),migrationAlgorithm:4}])),/unsupported/);for(const data of ['!bad','AAAA','gICAgICAgICAgIA='])assert.throws(()=>parseMigration('otpauth-migration://offline?data='+encodeURIComponent(data)));assert.throws(()=>parseMigration(migrationUri([])));assert.throws(()=>parseMigration(migrationUri([record()])+'&data=AA=='));});

test('compatible newer transfer versions and extra metadata preserve the exact OTP key',()=>{const original=record();for(const version of [0,1,2,3,42]){const url=new URL(migrationUri([original],{version})),bytes=Buffer.from(url.searchParams.get('data'),'base64');url.searchParams.set('data',Buffer.concat([bytes,field(100,Buffer.from('optional metadata'))]).toString('base64'));const parsed=parseMigration(url.toString());assert.equal(parsed.batch.version,version);assert.equal(parsed.records[0].secret,original.secret);assert.equal(core.totp(parsed.records[0],59),'287082');assert.throws(()=>collectMigration(collectMigration(null,parseMigration(migrationUri([original],{size:2,index:0,version}))),parseMigration(migrationUri([original],{size:2,index:1,version:version+1}))),/another transfer/);}});
